ci: js-tests are broken also on nix
internal/modules/cjs/loader.js:905
  throw err;
  ^
Error: Cannot find module 'xmlhttprequest'

Fixing this requires knowing npm, yarn and node,
so I will disable them for the moment

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>